- name: Change time zone
  timezone:
    name: "{{time_zone}}"

# - name: Upgrade the OS (apt-get dist-upgrade)
#   apt:
#     upgrade: dist
#     update_cache: yes
#   become: yes

- name: Download pihole to opt dir
  get_url:
    url: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
    dest: /opt/
    mode: 0755

- name: Execute pihole script
  shell: /opt/basic-install.sh
