 
---

- name: 'Change time zone'
  timezone:
    name: "{{time_zone}}"

- name: 'Template out Netplan YAML to configure networking'
  template:
    src: ./templates/99_config.yaml.tpl
    dest: /etc/netplan/99_config.yaml

- name: 'Applying Netplan Configuration'
  command: netplan apply
  become: yes
  become_method: sudo

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist
    update_cache: yes
  become: yes

- name: Update all packages to latest versions
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: 'Install CIFS-Utils'
  apt:
    name: cifs-utils
    state: present

- name: 'Install Pihole'
    get_url:
      url: https://install.pi-hole.net
      dest: /opt/basic-install.sh
    command: bash /opt/basic-install.sh
